### ISSUE TITLE
Order of React component lifecycle methods is unclear

### ISSUE THREAD

**Issue by goalaleo** [FullStack-HY/FullStack-Hy.github.io#125]
In Osa2 when first introducing lifecycle methods, `componentDidMount` is said to be called just before `render` is called for the first time
https://github.com/FullStack-HY/FullStack-Hy.github.io/blame/master/osa2.md#L1298

The same is said in Osa5, which references Osa2. Additionally, this is stated in Osa5
>Kyseessä on siis ns. lifecycle-metodi, jota React-kutsuu juuri ennen kuin komponentti ollaan renderöimässä ensimmäistä kertaa.

https://github.com/FullStack-HY/FullStack-Hy.github.io/blame/master/osa5.md#L528

However, the official React docs state that `componentDidMount` is called _after_ `render` is called. https://reactjs.org/docs/react-component.html#componentDidMount

Additionally the docs state
>Calling setState() in this method will trigger an extra rendering, but it will happen before the browser updates the screen. This guarantees that even though the render() will be called twice in this case, the user won’t see the intermediate state.

So the method `render` is called _before_ `componentDidMount`, but the actual rendering of the page, which is done by the browser, happens _after_ it.

Could the authors clarify this part a bit, and possibly introduce `componentWillMount`, which is actually called _before_ `render`?

**Comment by mluukkai** [comment]
Erinomainen huomio! Tämä jäi korjaamatta kun vaihdoin käytettävän metodin WillMountista DidMountiin.
